run_name: "ID_microcephaly_behvioral_all_layers"
ndd_gene_modules_folder_root: "/miridan-data/annaludmir/ndd_gene_modules/"

output_folder: "results/enrichment_results/"
ges_results_folder: "results/ges_score_results/ges_score_for_all_layers_20251225"
gene_list_path: "data/genes/ID_microcephaly_behvioral.csv"
gmt_folder: "data/genes/"

analysis_mode: "gsea"     # or "deseq" or "both"

gsea:
  min_ges_score_threshold: 1
  
deseq:
  pseudobulk_folder: "data/.../psb/"
  gene_names: "data/.../genes_100cells.txt"

column_conditions_for_gsea:
  Region:
    - "Cerebellum"
    - "Diencephalon"
    - "Midbrain"
    - "Forebrain"
    - "Hindbrain"
    - "Pons"
    - "Medulla"
    - "Telencephalon"
    
  CellClass:
    - "Radial glia"
    - "Neuronal IPC"
    - "Neuron"
    - "Glioblast"
    - "Neuroblast"

  RegionsGeneral:
    - "Forebrain_General"
    - "Hindbrain_General"
    - "Midbrain_General"

keep_only_significant: true
nes_keep_threshold: 1.5