ndd_gene_modules_folder_root: "/Users/anyaden/Git/ndd_gene_modules/"

output_folder: "data/enrichment_results/"
ges_results_folder: "results/ges_results/"
gmt_folder: "data/genes/"

data_type: cortex                # or data_all
analysis_mode: "gsea"     # or "deseq" or "both"

gsea:
  min_ges_score_threshold: 3

deseq:
  pseudobulk_folder: "data/.../psb/"
  gene_names: "data/.../genes_100cells.txt"

column_conditions_for_gsea:
  CellClass:
    - "Radial glia"
    - "Neuronal IPC"
    - "Neuron"
    - "Glioblast"
    - "Neuroblast"

  CellCyclePhase:
    - "G1"
    - "S"
    - "G2M"
    - "PostM"

  NPCs:
    - True

  Proliferating:
    - True

  Differentiating:
    - True

  Proliferating_NonCycling:
    - True

  Differentiating_NonCycling:
    - True