ndd_gene_modules_folder_root: "/Users/anyaden/Git/ndd_gene_modules/"

data_type: cortex                # or data_all
output_folder: "data/enrichment_results/"
gmt_folder: "data/ges_results_1/"

gsea:
  enabled: true
  min_ges_score_threshold: 3

deseq:
  enabled: false
  pseudobulk_folder: "data/.../psb/"
  gene_names: "data/.../genes_100cells.txt"

column_conditions_for_gsea:
  CellClass:
    - "Radial glia"
    - "Neuronal IPC"
    - "Neuron"
    - "Glioblast"
    - "Neuroblast"

  CellCyclePhase:
    - "G1"
    - "S"
    - "G2M"
    - "PostM"

  NPCs:
    derived:
      boolean_expr: "CellClass in ['Radial glia', 'Neuronal IPC']"
    conditions:
      - True

  Proliferating:
    derived:
      boolean_expr: "(CellClass in ['Radial glia', 'Neuronal IPC']) and (CellCycleFraction > 0.4)"
    conditions:
      - True

  Differentiating:
    derived:
      boolean_expr: "(CellClass in ['Neuroblast', 'Neuron', 'Glioblast']) and (CellCycleFraction > 0.4)"
    conditions:
      - True

  Proliferating_NonCycling:
    derived:
      boolean_expr: "(CellClass in ['Radial glia', 'Neuronal IPC']) and (CellCycleFraction <= 0.4)"
    conditions:
      - True

  Differentiating_NonCycling:
    derived:
      boolean_expr: "(CellClass in ['Neuroblast', 'Neuron', 'Glioblast']) and (CellCycleFraction <= 0.4)"
    conditions:
      - True