ndd_gene_modules_folder_root: "/Users/anyaden/Git/ndd_gene_modules/"

output_folder: "data/enrichment_results/"
ges_results_folder: "results/ges_results/"
gmt_folder: "data/genes/"

data_type: data_all                # or data_all
analysis_mode: "gsea"     # or "deseq" or "both"

gsea:
  min_ges_score_threshold: 3
  
deseq:
  pseudobulk_folder: "data/.../psb/"
  gene_names: "data/.../genes_100cells.txt"

column_conditions_for_gsea:
  region_general
    - "Radial Glia"
    - "Cerebellum"
    - "Diencephalon"
    - "Fibroblast"
    - "Glioblast"
    - "Forebrain_general"
    - "hindbrain_general"
    - "Immune"
    - "Midbrain_general"
    - "Neural_crest"
    - "IPC"
    - "Neuroblast"
    - "Neuron"
    - "Oligo"
    - "Forebrain"
    - "Hindbrain"
    - "Placodes"
    - "Pons"
    - "Medulla"
    - "Telencephalon"
    - "Vascular"