name_of_run: "ges_score_for_all_layers_proliferating"
ndd_gene_modules_folder_root: "/miridan-data/annaludmir/ndd_gene_modules"
data_path: "data/human_dev.h5ad"
output_folder: "results/ges_score_results/"

column_conditions:
  ProliferatingRegions:
    derived:
      rules:
        Forebrain: "(Region in ['Diencephalon', 'Forebrain', 'Telencephalon']) & (cell_cycle_score > 0.004)"
        Hindbrain: "(Region in ['Hindbrain', 'Cerebellum', 'Pons', 'Medulla']) & (cell_cycle_score > 0.004)"
        Midbrain: "(Region in ['Midbrain']) & (cell_cycle_score > 0.004)"
    conditions: ["Forebrain", "Hindbrain", "Midbrain"]

expression_threshold: 0.05
chemistry: "v3"
permutations: false
normalize_data: true
# n_permutations: 500  # optional
