name_of_run: "ges_score_for_all_layers"
ndd_gene_modules_folder_root: "/miridan-data/annaludmir/ndd_gene_modules"
data_path: "data/human_dev_GRCh38-3.0.0_all_layers_cleaned.h5ad"
output_folder: "results/ges_score_results/"

column_conditions:
  Region:
    - "Cerebellum"
    - "Diencephalon"
    - "Midbrain"
    - "Forebrain"
    - "Hindbrain"
    - "Pons"
    - "Medulla"
    - "Telencephalon"
    - "Head"
    - "Brain"

expression_threshold: 0.05
# chemistry: "v3"
permutations: false
# n_permutations: 500  # optional
