name_of_run: "ges_score_for_cortex"
ndd_gene_modules_folder_root: "/miridan-data/annaludmir/ndd_gene_modules/"
data_path: "data/Cortex_EMX1_louvain3_passedQC_PostM_rev1.h5ad"
output_folder: "results/ges_score_results/"

column_conditions:
  CellClass:
    - "Radial glia"
    - "Neuronal IPC"
    - "Neuron"
    - "Glioblast"
    - "Neuroblast"

  NPCs:
    derived:
      boolean_expr: "CellClass in ['Radial glia', 'Neuronal IPC']"
    conditions:
      - True
      - False

  Proliferation_CellCycle:
    derived:
      rules:
        Proliferating_Cycling: "(CellClass in ['Radial glia', 'Neuronal IPC']) and (CellCycleFraction > 0.4)"
        Differentiating_Cycling: "(CellClass in ['Neuroblast', 'Neuron', 'Glioblast']) and (CellCycleFraction > 0.4)"
        Proliferating_NonCycling: "(CellClass in ['Radial glia', 'Neuronal IPC']) and (CellCycleFraction <= 0.4)"
        Differentiating_NonCycling: "(CellClass in ['Neuroblast', 'Neuron', 'Glioblast']) and (CellCycleFraction <= 0.4)"
    conditions: ["Proliferating_Cycling", "Differentiating_Cycling", "Proliferating_NonCycling", "Differentiating_NonCycling"]
      
expression_threshold: 0.05
normalize_data: true
chemistry: "v3"
permutations: false
# n_permutations: 500  # optional
